name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Debug current dir
      run: |
        pwd
        ls -al

   # SSH and Deployment Steps
    - name: Initialize and Setup SSH
      run: |
        mkdir -p ~/.ssh
        chmod 700 ~/.ssh
        touch ~/.ssh/known_hosts
        chmod 644 ~/.ssh/known_hosts
        eval $(ssh-agent -s)
        ssh-keyscan -H ${{ secrets.DROPLET_IP }} >> ~/.ssh/known_hosts
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > id_rsa
        chmod 600 id_rsa
        ssh-add id_rsa
        

    - name: Deploy to Existing DigitalOcean Droplet
      run: |
        scp -r ./* ${{ secrets.SSH_USER }}@${{ secrets.DROPLET_IP }}:/var/www/obinnaCICD/
      env:
        SSH_USER: ${{ secrets.SSH_USER }}
