name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Debug current dir
      run: |
        pwd
        ls -al

    - name: Install SSH key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.REMOTE_HOST }} >> ~/.ssh/known_hosts
        echo "${{ secrets.SSH_PASSPHRASE }}" > passphrase.txt
        ssh-add -p passphrase.txt ~/.ssh/id_rsa < /dev/null
      env:
        SSH_AUTH_SOCK: /tmp/ssh_agent.sock
            

    - name: Deploy to Existing DigitalOcean Droplet
      run: |
        scp -r ./* ${{ secrets.SSH_USER }}@${{ secrets.DROPLET_IP }}:/var/www/obinnaCICD/
      env:
        SSH_USER: ${{ secrets.SSH_USER }}
