name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    # Debug current dir (Optional - only for debugging purposes)
    - name: Debug current dir
      run: |
        pwd
        ls -al

    # SonarQube Analysis
    - name: SonarQube Analysis
      uses: sonarsource/sonarcloud-github-action@master
      with:
        args: >
          -Dsonar.projectKey=obiminion_CI-CD-Pipeline
          -Dsonar.organization=obiminion
      env:
        GITHUB_TOKEN: ${{ secrets.MY_GH_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

    # Set up Java for OWASP Dependency-Check
    - name: Set up Java
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'

    # Download and Unzip Dependency-Check for OWASP
    - name: Download and Unzip Dependency-Check
      run: |
        wget https://github.com/jeremylong/DependencyCheck/releases/download/v8.4.0/dependency-check-8.4.0-release.zip
        unzip dependency-check-8.4.0-release.zip

    # Run OWASP Dependency-Check with disabled assembly identification
    - name: Run OWASP Dependency-Check
      run: ./dependency-check/bin/dependency-check.sh --project "My Project" --scan . --disableAssembly

    # Build Docker Image
    - name: Build Docker Image
      run: docker build -t my-web-app .

    # Trivy Scan
    - name: Trivy Scan
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: 'my-web-app'
        token: ${{ secrets.MY_GH_TOKEN }}

     # Setup Terraform
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1

    # Terraform Init
    - name: Terraform Init
      run: terraform init

    # Terraform Apply to provision droplet
    - name: Terraform Apply
      run: terraform apply -auto-approve -input=false
      env:
        DO_TOKEN: ${{ secrets.DO_TOKEN }}
        SSH_KEY: ${{ secrets.SSH_KEY }}

    # SSH into DigitalOcean droplet and Deploy
    - name: Deploy to DigitalOcean
      run: |
        # SSH into the DO droplet and deploy Docker container
        ssh -o "StrictHostKeyChecking=no" ${{ secrets.SSH_USER }}@${{ steps.set-ip.outputs.droplet_ip }} "
          docker pull my-web-app:latest
          docker stop web-container || true
          docker rm web-container || true
          docker run --name web-container -d -p 80:80 my-web-app:latest
        "
      env:
        SSH_USER: ${{ secrets.SSH_USER }}
        SSH_KEY: ${{ secrets.SSH_KEY }}
